---
_extends: .github

repository:
  name: toxic
  description: An ncurses-based Tox client
  topics: tox, console, chat

branches:
  - name: "master"
    protection:
      required_status_checks:
        contexts:
          - Codacy/PR Quality Review
          - CodeFactor
          - Travis CI - Pull Request
          - code-review/reviewable
